### ISSUE TITLE
saptune and customer-specific customizations

### ISSUE THREAD

**Issue by rbeldin** [HouzuoGuo/saptune#4]
I'm trying to understand some issues with saptune on SLES12SP3 where /etc/security/limits.conf are apparently getting reset to default values of 32800 even after specific values are set.   I'm trying to figure out a way to see how I can track these changes.  System auditing at this point seems to be the best idea. 

I started examining  the code and wondered about hard-coded values like the ones seen below: 

 81         // Raise maximum file descriptors to at least 32800
 82         for _, val := range []*system.SecurityLimitInt{&newPrepare.LimitNofileSapsysSoft, &newPrepare.LimitNofileSapsysHard, &newPrepare.LimitNofileSdbaSoft, &newPrepare.LimitNofileSdba    Hard, &newPrepare.LimitNofileDbaSoft, &newPrepare.LimitNofileDbaHard} {
 83                 switch *val {
 84                 case system.SecurityLimitUnlimitedValue:
 85                         // nothing to do, value remain untouched
 86                 default:
 87                         if *val < 32800 {
 88                                 *val = 32800
 89                         }
 90                 }
 91         }

Would it not make sense to have these sorts of hard-coded values (and others) in some sort of table, external to saptune so that changes could be made without recompiling the program?  It almost seems like a 'meta' solution or note would make this more flexible in the long term.   

I admit that I don't know much about the design but I found it curious and was just trying to understand some more.

**Comment by HouzuoGuo** [comment]
Greetings from Helsinki!

The mission of saptune as a new solution was to offer a tool for assessing systems and apply best practice as laid out in guidelines provided by SAP. The logic and rationale of tuned parameters are specified in SAP notes, and the software design was agreed by all stakeholders in SUSE and SAP.

For the ultimate objective of system tuning, the design does not encourage customer to tune saptune in order to tune system, instead, the tool enforces SAP guidelines while allowing customer to apply their own tunable values better than SAP's default, e.g. sysctl.conf. Saptune, sensing that customer's decision is already superior to SAP's guideline, will stay out of the way and concluding that system tunables are compliant.

Take the number-of-open-FD limit in your example, the best practice composed by SAP says they shall be greater than `32800` specifically - that is the logic, and the logic does not say the value shall be greater than an arbitrary value defined by customer. Therefore, the constant `32800`, along with many others, are program logic instead of data.

For system assessment, the subcommand "verify" or "simulate" will help for the future.

**Comment by HouzuoGuo** [comment]
To elaborate little further given the development of saptune in 2017, apparently several folks at SAP want to make it a `tuned` replacement, which encourages customers to tune their system by tuning `saptune` - an unnecessary level of complication. The new direction was never in the vision and scope of the original design, and goes against the mission of having a tool that permits customer to use their best judgement and common knowledge to apply tuning techniques.

**Comment by rbeldin** [comment]
Thanks for explanation.   It does indeed seem that saptune use is migrating beyond what its original intentions were.  Sometimes that is a good thing, sometimes not. 

 In the issue I worked on, the end user had systems that needed values that exceeded the builtin values, for example the settings for limits.conf.   This was needed (I presume) because of the large scale of the systems, with an excess of 12TB of RAM and more than 400 processors.   The end user was getting frustrated by running saptune, making changes to limits.conf in excess of the default values and finding after rebooting that the values had reverted to the defaults. 

I found a workaround by doing: 

1. saptune solution apply HANA
2. saptune solution revert HANA
3. edit limits.conf
4. saptune solution apply HANA

I think this works because it forces the initial saved_state in /var/lib/saptune/saved_state to be initialized with the 'new' (user-implemented) default values.   I tried following the logic in saptune/app/app.go where I think this is done, but my lack of familiarity with Go limits my understanding.    Since saptune doesn't have an initial state the first time that a solution is applied, what is saved is the set of values that it set.   I'm not sure if this is correct understanding or not but it feels that way.

**Comment by HouzuoGuo** [comment]
Similar to applying individual tuning techniques (note, blog, etc), applying for an entire solution saves the old state memorised per individual tuning technique, and reverting an entire solution reverts all of the memorised state together. This can indeed cause confusion like the one you mentioned. Please get in touch with colleagues at SUSE/saptune to print a reminder output in such case.

**Comment by rbeldin** [comment]
Thanks very much for the feedback.   I'm working with SUSE already and will
discuss it further.  Again, thanks for your time.

Rick
-- 
Rick Beldin
HPE Master Technologist, ERT
HPE Pointnext
Tel:  +1 470 2129073  Email: rick.beldin@hpe.com
Physical: 5555 Windward Parkway West, Alpharetta GA 30004

**Comment by HouzuoGuo** [comment]
Always glad to help!
